### ISSUE TITLE
Deployment Issues

### ISSUE THREAD

**Issue by glabelle69** [aws-quickstart/quickstart-ibm-icp-for-data#10]
When running the scripts, I get the following errors. Any idea as to what would cause this:

<img width="1123" alt="Screen Shot 2019-05-31 at 9 40 15 PM" src="https://user-images.githubusercontent.com/22181026/58741901-03750800-83ed-11e9-9e20-c868dd7e9d28.png">

**Comment by glabelle69** [comment]
[19/06/01 01:37:19.741582 UTC] 7f612fcad700 E __main__(1762) runAnsiblePlaybook : ERROR: Error calling ansible-playbook. Return code: 4
	Error calling ansible-playbook. Return code: 4
	Exception stack (most recent call first):
	bootstrap.py(1757) [runAnsiblePlaybook] - raise Exception("Error calling ansible-playbook. Return code: %s" % retcode)
	Frame stack (most recent call first):
	bootstrap.py(1762) [runAnsiblePlaybook] - TR.error(methodName,"ERROR: %s" % e, e)
	bootstrap.py(2437) [main] - self.runAnsiblePlaybook(playbookPath=setMaxMapCountPlaybookPath,targetNodes="all",logFilePath=logFilePath)
	bootstrap.py(2550) [<module>] - mainInstance.main(sys.argv)
[19/06/01 01:37:19.742419 UTC] 7f612fcad700 E __main__(2493) main : ERROR: Error calling ansible-playbook. Return code: 4
	Error calling ansible-playbook. Return code: 4
	Exception stack (most recent call first):
	bootstrap.py(1757) [runAnsiblePlaybook] - raise Exception("Error calling ansible-playbook. Return code: %s" % retcode)
	bootstrap.py(2437) [main] - self.runAnsiblePlaybook(playbookPath=setMaxMapCountPlaybookPath,targetNodes="all",logFilePath=logFilePath)
	Frame stack (most recent call first):
	bootstrap.py(2493) [main] - TR.error(methodName,"ERROR: %s" % e, e)
	bootstrap.py(2550) [<module>] - mainInstance.main(sys.argv)
[19/06/01 01:37:20.150046 UTC] 7f612fcad700 3 __main__(1227) _deleteSSMParameters : Post install cleanup. Deleted SSM parameters: ['/IBM-Cloud-Private-for-Data/ip-10-10-10-190.us-east-2.compute.internal', '/IBM-Cloud-Private-for-Data/

**Comment by glabelle69** [comment]
[bootstrap.log](https://github.com/aws-quickstart/quickstart-ibm-icp-for-data/files/3243282/bootstrap.log)

**Comment by shaithal** [comment]
@petervansickel  looks like ICP bootstrap is failing to run playbooks. Can you please check and help us understand the issue.

**Comment by vsnyc** [comment]
Based on the error, RRSet is not permitted, I think it is related to the parameters chosen to deploy the stack. @glabelle69, could you provide the list of parameter used? You can grab it from the output of the following command, substituting the Region and the stack name.
`aws cloudformation --region $REGION describe-stacks --stack $STACK_NAME`

**Comment by glabelle69** [comment]
{

    "Stacks": [

        {

            "StackId": "arn:aws:cloudformation:us-east-2:694286674523:stack/IBM-Cloud-Private/754a3770-84a1-11e9-9fc6-024d9c0f9898",

            "StackName": "IBM-Cloud-Private",

            "Description": "Root template for an IBM Cloud Private deployment. This is the root template for a collection of nested stacks that make up the full ICP deployment. **WARNING** This template creates EC2 instances and related resources. You will be billed for the AWS resources used if you create a stack from this template. (qs-1p8m99osu)",

            "Parameters": [

                {

                    "ParameterKey": "InceptionTimeout",

                    "ParameterValue": "7200"

                },

                {

                    "ParameterKey": "ResourceOwner",

                    "ParameterValue": "ICP-Quickstart"

                },

                {

                    "ParameterKey": "QSS3KeyPrefix",

                    "ParameterValue": "quickstart-ibm-cloud-private/"

                },

                {

                    "ParameterKey": "ICPDeploymentLogsBucketName",

                    "ParameterValue": "icp4d-logs"

                },

                {

                    "ParameterKey": "StorageIOPS",

                    "ParameterValue": "8000"

                },

                {

                    "ParameterKey": "VPCCIDR",

                    "ParameterValue": "10.10.0.0/16"

                },

                {

                    "ParameterKey": "AvailabilityZoneCount",

                    "ParameterValue": "1"

                },

                {

                    "ParameterKey": "ClusterCIDR",

                    "ParameterValue": "192.168.0.0/16"

                },

                {

                    "ParameterKey": "VPCDomain",

                    "ParameterValue": "app"

                },

                {

                    "ParameterKey": "WhichClusterLBAddress",

                    "ParameterValue": "UseClusterName"

                },

                {

                    "ParameterKey": "AdminPassword",

                    "ParameterValue": "****"

                },

                {

                    "ParameterKey": "ClusterPKIRootPath",

                    "ParameterValue": ""

                },

                {

                    "ParameterKey": "ExcludedMgmtServices",

                    "ParameterValue": "istio,vulnerability-advisor,custom-metrics-adapter"

                },

                {

                    "ParameterKey": "PrivateSubnetCIDR",

                    "ParameterValue": "10.10.10.0/20"

                },

                {

                    "ParameterKey": "QSS3BucketName",

                    "ParameterValue": "aws-quickstart"

                },

                {

                    "ParameterKey": "ExternalApplicationLocation",

                    "ParameterValue": "0.0.0.0/0"

                },

                {

                    "ParameterKey": "InstallationTimeout",

                    "ParameterValue": "7200"

                },

                {

                    "ParameterKey": "AppSubdomainPrefix",

                    "ParameterValue": "apps"

                },

                {

                    "ParameterKey": "ManagementNodeCount",

                    "ParameterValue": "1"

                },

                {

                    "ParameterKey": "MasterNodeCount",

                    "ParameterValue": "1"

                },

                {

                    "ParameterKey": "WorkerNodeInstanceType",

                    "ParameterValue": "m5.xlarge"

                },

                {

                    "ParameterKey": "MasterNodeInstanceType",

                    "ParameterValue": "m5.2xlarge"

                },

                {

                    "ParameterKey": "ExternalSSHLocation",

                    "ParameterValue": "0.0.0.0/32"

                },

                {

                    "ParameterKey": "ProxyNodeCount",

                    "ParameterValue": "1"

                },

                {

                    "ParameterKey": "WorkerNodeCount",

                    "ParameterValue": "2"

                },

                {

                    "ParameterKey": "VPCName",

                    "ParameterValue": "IBMCloudPrivateVPC"

                },

                {

                    "ParameterKey": "ClusterDomain",

                    "ParameterValue": "cluster.local"

                },

                {

                    "ParameterKey": "BootNodeInstanceType",

                    "ParameterValue": "m5.xlarge"

                },

                {

                    "ParameterKey": "VulnerabilityAdvisorNodeCount",

                    "ParameterValue": "0"

                },

                {

                    "ParameterKey": "ApplicationStorageMountPoint",

                    "ParameterValue": "/mnt/storage"

                },

                {

                    "ParameterKey": "PublicSubnetCIDR",

                    "ParameterValue": "10.10.20.0/22"

                },

                {

                    "ParameterKey": "PrivateSubnets",

                    "ParameterValue": "10.10.10.0/24"

                },

                {

                    "ParameterKey": "ProxyNodeInstanceType",

                    "ParameterValue": "m5.xlarge"

                },

                {

                    "ParameterKey": "PublicSubnets",

                    "ParameterValue": "10.10.20.0/24"

                },

                {

                    "ParameterKey": "ClusterName",

                    "ParameterValue": "mycluster"

                },

                {

                    "ParameterKey": "ManagementNodeInstanceType",

                    "ParameterValue": "m5.2xlarge"

                },

                {

                    "ParameterKey": "AdminUser",

                    "ParameterValue": "admin"

                },

                {

                    "ParameterKey": "ExternalICPAdminLocation",

                    "ParameterValue": "0.0.0.0/0"

                },

                {

                    "ParameterKey": "VulnerabilityAdvisorNodeInstanceType",

                    "ParameterValue": "m5.2xlarge"

                },

                {

                    "ParameterKey": "VPCSubdomainPrefix",

                    "ParameterValue": ""

                },

                {

                    "ParameterKey": "EBSVolumeType",

                    "ParameterValue": "gp2"

                },

                {

                    "ParameterKey": "ICPVersion",

                    "ParameterValue": "3.1.2"

                },

                {

                    "ParameterKey": "AvailabilityZones",

                    "ParameterValue": "us-east-2a"

                },

                {

                    "ParameterKey": "HostedZoneId",

                    "ParameterValue": "ZUOXQRU0X6TT3"

                },

                {

                    "ParameterKey": "WhichProxyLBAddress",

                    "ParameterValue": "UseProxyELBName"

                },

                {

                    "ParameterKey": "KeyName",

                    "ParameterValue": "icp4d-quickstart"

                },

                {

                    "ParameterKey": "KeyFilePath",

                    "ParameterValue": ""

                },

                {

                    "ParameterKey": "ClusterPKIBucketName",

                    "ParameterValue": ""

                },

                {

                    "ParameterKey": "ServiceCIDR",

                    "ParameterValue": "172.16.0.0/24"

                },

                {

                    "ParameterKey": "CustomArtifactsPath",

                    "ParameterValue": ""

                }

            ],

            "CreationTime": "2019-06-01T19:14:20.600Z",

            "RollbackConfiguration": {

                "RollbackTriggers": []

            },

            "StackStatus": "CREATE_FAILED",

            "StackStatusReason": "The following resource(s) failed to create: [InstallationCompleted, ClusterDNSEntries]. ",

            "DisableRollback": true,

            "NotificationARNs": [],

            "Capabilities": [

                "CAPABILITY_NAMED_IAM",

                "CAPABILITY_AUTO_EXPAND"

            ],

            "Tags": [],

            "EnableTerminationProtection": false,

            "DriftInformation": {

                "StackDriftStatus": "NOT_CHECKED"

            }

        }

    ]

}

**Comment by glabelle69** [comment]
{
    "Stacks": [
        {
            "StackId": "arn:aws:cloudformation:us-east-2:694286674523:stack/IBM-Cloud-Private/754a3770-84a1-11e9-9fc6-024d9c0f9898",
            "StackName": "IBM-Cloud-Private",
            "Description": "Root template for an IBM Cloud Private deployment. This is the root template for a collection of nested stacks that make up the full ICP deployment. **WARNING** This template creates EC2 instances and related resources. You will be billed for the AWS resources used if you create a stack from this template. (qs-1p8m99osu)",
            "Parameters": [
                {
                    "ParameterKey": "InceptionTimeout",
                    "ParameterValue": "7200"
                },
                {
                    "ParameterKey": "ResourceOwner",
                    "ParameterValue": "ICP-Quickstart"
                },
                {
                    "ParameterKey": "QSS3KeyPrefix",
                    "ParameterValue": "quickstart-ibm-cloud-private/"
                },
                {
                    "ParameterKey": "ICPDeploymentLogsBucketName",
                    "ParameterValue": "icp4d-logs"
                },
                {
                    "ParameterKey": "StorageIOPS",
                    "ParameterValue": "8000"
                },
                {
                    "ParameterKey": "VPCCIDR",
                    "ParameterValue": "10.10.0.0/16"
                },
                {
                    "ParameterKey": "AvailabilityZoneCount",
                    "ParameterValue": "1"
                },
                {
                    "ParameterKey": "ClusterCIDR",
                    "ParameterValue": "192.168.0.0/16"
                },
                {
                    "ParameterKey": "VPCDomain",
                    "ParameterValue": "app"
                },
                {
                    "ParameterKey": "WhichClusterLBAddress",
                    "ParameterValue": "UseClusterName"
                },
                {
                    "ParameterKey": "AdminPassword",
                    "ParameterValue": "****"
                },
                {
                    "ParameterKey": "ClusterPKIRootPath",
                    "ParameterValue": ""
                },
                {
                    "ParameterKey": "ExcludedMgmtServices",
                    "ParameterValue": "istio,vulnerability-advisor,custom-metrics-adapter"
                },
                {
                    "ParameterKey": "PrivateSubnetCIDR",
                    "ParameterValue": "10.10.10.0/20"
                },
                {
                    "ParameterKey": "QSS3BucketName",
                    "ParameterValue": "aws-quickstart"
                },
                {
                    "ParameterKey": "ExternalApplicationLocation",
                    "ParameterValue": "0.0.0.0/0"
                },
                {
                    "ParameterKey": "InstallationTimeout",
                    "ParameterValue": "7200"
                },
                {
                    "ParameterKey": "AppSubdomainPrefix",
                    "ParameterValue": "apps"
                },
                {
                    "ParameterKey": "ManagementNodeCount",
                    "ParameterValue": "1"
                },
                {
                    "ParameterKey": "MasterNodeCount",
                    "ParameterValue": "1"
                },
                {
                    "ParameterKey": "WorkerNodeInstanceType",
                    "ParameterValue": "m5.xlarge"
                },
                {
                    "ParameterKey": "MasterNodeInstanceType",
                    "ParameterValue": "m5.2xlarge"
                },
                {
                    "ParameterKey": "ExternalSSHLocation",
                    "ParameterValue": "0.0.0.0/32"
                },
                {
                    "ParameterKey": "ProxyNodeCount",
                    "ParameterValue": "1"
                },
                {
                    "ParameterKey": "WorkerNodeCount",
                    "ParameterValue": "2"
                },
                {
                    "ParameterKey": "VPCName",
                    "ParameterValue": "IBMCloudPrivateVPC"
                },
                {
                    "ParameterKey": "ClusterDomain",
                    "ParameterValue": "cluster.local"
                },
                {
                    "ParameterKey": "BootNodeInstanceType",
                    "ParameterValue": "m5.xlarge"
                },
                {
                    "ParameterKey": "VulnerabilityAdvisorNodeCount",
                    "ParameterValue": "0"
                },
                {
                    "ParameterKey": "ApplicationStorageMountPoint",
                    "ParameterValue": "/mnt/storage"
                },
                {
                    "ParameterKey": "PublicSubnetCIDR",
                    "ParameterValue": "10.10.20.0/22"
                },
                {
                    "ParameterKey": "PrivateSubnets",
                    "ParameterValue": "10.10.10.0/24"
                },
                {
                    "ParameterKey": "ProxyNodeInstanceType",
                    "ParameterValue": "m5.xlarge"
                },
                {
                    "ParameterKey": "PublicSubnets",
                    "ParameterValue": "10.10.20.0/24"
                },
                {
                    "ParameterKey": "ClusterName",
                    "ParameterValue": "mycluster"
                },
                {
                    "ParameterKey": "ManagementNodeInstanceType",
                    "ParameterValue": "m5.2xlarge"
                },
                {
                    "ParameterKey": "AdminUser",
                    "ParameterValue": "admin"
                },
                {
                    "ParameterKey": "ExternalICPAdminLocation",
                    "ParameterValue": "0.0.0.0/0"
                },
                {
                    "ParameterKey": "VulnerabilityAdvisorNodeInstanceType",
                    "ParameterValue": "m5.2xlarge"
                },
                {
                    "ParameterKey": "VPCSubdomainPrefix",
                    "ParameterValue": ""
                },
                {
                    "ParameterKey": "EBSVolumeType",
                    "ParameterValue": "gp2"
                },
                {
                    "ParameterKey": "ICPVersion",
                    "ParameterValue": "3.1.2"
                },
                {
                    "ParameterKey": "AvailabilityZones",
                    "ParameterValue": "us-east-2a"
                },
                {
                    "ParameterKey": "HostedZoneId",
                    "ParameterValue": "ZUOXQRU0X6TT3"
                },
                {
                    "ParameterKey": "WhichProxyLBAddress",
                    "ParameterValue": "UseProxyELBName"
                },
                {
                    "ParameterKey": "KeyName",
                    "ParameterValue": "icp4d-quickstart"
                },
                {
                    "ParameterKey": "KeyFilePath",
                    "ParameterValue": ""
                },
                {
                    "ParameterKey": "ClusterPKIBucketName",
                    "ParameterValue": ""
                },
                {
                    "ParameterKey": "ServiceCIDR",
                    "ParameterValue": "172.16.0.0/24"
                },
                {
                    "ParameterKey": "CustomArtifactsPath",
                    "ParameterValue": ""
                }
            ],
            "CreationTime": "2019-06-01T19:14:20.600Z",
            "RollbackConfiguration": {
                "RollbackTriggers": []
            },
            "StackStatus": "CREATE_FAILED",
            "StackStatusReason": "The following resource(s) failed to create: [InstallationCompleted, ClusterDNSEntries]. ",
            "DisableRollback": true,
            "NotificationARNs": [],
            "Capabilities": [
                "CAPABILITY_NAMED_IAM",
                "CAPABILITY_AUTO_EXPAND"
            ],
            "Tags": [],
            "EnableTerminationProtection": false,
            "DriftInformation": {
                "StackDriftStatus": "NOT_CHECKED"
            }
        }
    ]
}

**Comment by vsnyc** [comment]
When you specify a HostedZoneId, your VPCDomain should match your hosted zone. Looking at the error, your configuration should be:
VPCDomain: `bigdata-gurus.com`
HostedZoneId: as provided above.
VPCSubdomainPrefix: empty string is acceptable, you could also give something more meaningful to keep the root domain well partitioned, e.g. `icpd`

The other parameters look okay on a quick glance, please compare with the non-ha configuration just to be sure. 

Once the stack is deployed you should be able the ICPD console at: `https://${ClusterName}.${VPCSubdomainPrefix}.${VPCDomain}:31843/`; i.e., 
`https://mycluster.icpd.bigdata-gurus.com:31843/`

**Comment by vsnyc** [comment]
Resolving this as a duplicate of #9, have followed up on that again.
