### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Dgupta2901** [aws-quickstart/quickstart-ibm-icp-for-data#24]
Hi,
I have been trying to install IBM Cloud Pak for Data using the Quick guide provided on AWS but continuously getting the same error of invalid bucket name. I have verified it multiple times but i am not able to pass that error. I would appreciate any guidance.

Thanks
[bootstrap (1).log](https://github.com/aws-quickstart/quickstart-ibm-icp-for-data/files/5067754/bootstrap.1.log)
[parameter.txt](https://github.com/aws-quickstart/quickstart-ibm-icp-for-data/files/5067755/parameter.txt)

**Comment by shaithal** [comment]
Update  "ParameterValue": "s3://ibm-logs-2020/" to ibm-logs-2020. Here we expect just bucket name.  Not uri format.

**Comment by Dgupta2901** [comment]
Thanks for that, i am just launching it now. Hopefully i should be able to get it working now. Thanks once again

**Comment by Dgupta2901** [comment]
Hi,
I was able to successfully complete the installation. While running the following command to install PA

./cpd-linux -c EFS -r ./repo.yaml -a lite -n zen --transfer-image-to $(oc get route -n openshift-image-registry | tail -1| awk '{print $2}')/zen --target-registryusername $(oc whoami | sed 's/://g') --target-registry-password $(oc serviceaccounts get-token cpdtoken) --cluster-pull-prefix image-registry.openshift-image-registry.svc:5000/zen -o override.yaml --insecure-skip-tls-verify

I get an error as override.yaml does not exist, there are following two files except the one in the command. i tried creating a file but got the error ( snapshot is attached for reference)
override_ocs.yaml
override_px.yaml

I am not to run this command successfully, its giving an error

![Error-icpd](https://user-images.githubusercontent.com/46271639/90132976-0a015c80-ddb2-11ea-993f-7a4d8136a627.jpg)

Thanks

**Comment by shaithal** [comment]
Hi, I believe you are trying to install planning analytics? Can you help me with the commands you ran?

**Comment by Dgupta2901** [comment]
Hi,

Yes you are correct, i was trying to install PA. I just went ahead and deleted the existing stack and created a new stack using the quick startup guide and then followed the steps outlined in the IBM PA Installation on IBM Cloud Pak for Data ( https://www.ibm.com/support/producthub/icpdata/docs/content/SSQNUZ_current/svc-pa/pa-install.html) and was able to get it working. 
I still need to work out the underlying structure for PA , i am working on it.
I really appreciate your assistance in resolving the installation of ICP for Data on AWS.

Thanks

**Comment by shaithal** [comment]
Glad to know that it worked. Let me know if we can  close this issue.
