### ISSUE TITLE
Failed to create IBM Cloud Pak for Data on the AWS Cloud

### ISSUE THREAD

**Issue by dipdeb** [aws-quickstart/quickstart-ibm-icp-for-data#41]
Hi team,
We're trying to bring up a "IBM Cloud Pak for Data on the AWS Cloud" by following the quickstart (https://aws-quickstart.github.io/quickstart-ibm-icp-for-data/). After creating bootnode, master nodes, bootstrap and workers, when
the openshift installation is going on we are getting this error and the installation is rolling back after that. We're able to 
get the logs in s3 output bukcet.

lite_apply.log
`[INFO] [2021-02-04 14:05:39-0385] Arch override not found. Assuming default architecture x86_64
[INFO] [2021-02-04 14:05:39-0392] Parsing custom YAML file /ibm/repo.yaml
[INFO] [2021-02-04 14:05:39-0393] Overwritten default download settings using /ibm/repo.yaml
[INFO] [2021-02-04 14:05:39-0395] 1 file servers and 1 registries detected from current configuration
[INFO] [2021-02-04 14:05:39-0397] Server configure files validated

*** Parsing assembly data and generating a list of charts and images for download ***

[ERROR] [2021-02-04 14:05:39-0747] Assembly lite requires cpd-cli version 3.5.2 or newer. Currently using 3.5.1
[ERROR] [2021-02-04 14:05:39-0748] Error generating charts list. None of the servers defined in your repo file /ibm/repo.yaml provides file for assembly lite
[ERROR] [2021-02-04 14:05:39-0750] Exiting due to error. Please check /ibm/cpd-cli-workspace/logs/CPD-2021-02-04T14-05-39.log for details
[ERROR] 2021-02-04T14:05:39.751457Z Execution error:  exit status 1`

lite_install.log
`[INFO] [2021-02-04 14:05:40-0163] Arch override not found. Assuming default architecture x86_64
[INFO] [2021-02-04 14:05:41-0335] Parsing custom YAML file /ibm/repo.yaml
[INFO] [2021-02-04 14:05:41-0337] Overwritten default download settings using /ibm/repo.yaml
[INFO] [2021-02-04 14:05:41-0338] 1 file servers and 1 registries detected from current configuration
[INFO] [2021-02-04 14:05:41-0341] Server configure files validated

*** Parsing assembly data and generating a list of charts and images for download ***

[ERROR] [2021-02-04 14:05:41-0423] Assembly lite requires cpd-cli version 3.5.2 or newer. Currently using 3.5.1
[INFO] [2021-02-04 14:05:42-0556] Collecting cpd install information
[INFO] [2021-02-04 14:05:42-0562] Collecting operator pod log information
[INFO] [2021-02-04 14:05:42-0572] Pod cpd-install-operator not found
[INFO] [2021-02-04 14:05:42-0573] Collecting tiller pod log information
[INFO] [2021-02-04 14:05:42-0577] cpd tiller pod not found
[INFO] [2021-02-04 14:05:42-0579] Collecting configmap information
[INFO] [2021-02-04 14:05:42-0583] Creating the diag tarball
[WARNING] [2021-02-04 14:05:42-0590] Unable to collect the install/upgrade diag info: Failed to stat file /ibm/cpd-cli-workspace/install-diag/operator.log: stat /ibm/cpd-cli-workspace/install-diag/operator.log: no such file or directory
[ERROR] [2021-02-04 14:05:42-0591] Exiting due to error (Error generating charts list. None of the servers defined in your repo file /ibm/repo.yaml provides file for assembly lite). Please check /ibm/cpd-cli-workspace/logs/CPD-2021-02-04T14-05-40.log for details
[ERROR] 2021-02-04T14:05:42.592799Z Execution error:  exit status 1
`
The log CPD-2021-02-04T14-05-40.log is not with us as before getting back the bootnode is terminated. 

Is there something wrong we are doing or there's something else? Please, let us know.

**Comment by shaithal** [comment]
We are in the process of updating the quickstart and once done this should be fixed.

**Comment by dipdeb** [comment]
Thanks. If any update please let us know.

**Comment by shaithal** [comment]
Issue is fixed now. please try and let us know.

**Comment by dipdeb** [comment]
Hi, we have tried and it's working like charm!
Thanks!
