### ISSUE TITLE
What port is the plain-ICP dashboard running on?

### ISSUE THREAD

**Issue by durera** [aws-quickstart/quickstart-ibm-icp-for-data#7]
We've ran through the [quickstart](https://aws-quickstart.s3.amazonaws.com/quickstart-ibm-icp-for-data/doc/ibm-cloud-private-for-data-on-the-aws-cloud.pdf), and can access the ICP4data UI on port 31843 to verify the install worked, reasonably straightforward up to now:+1:  ... however, we're failing trying to work out how we can access the standard ICP UI dashboard as well.  

The port that the plain ICP dashboard runs on doesn't seem to be documented anywhere in the quickstart guide, or the logs from the deploy in AWS unless I've missed it, and I can't find anything in the ICP4D UI that links off to the main ICP UI either.

How do I get to the dashboard to, for example, deploy something from the ICP catalogue into this instance?

**Comment by vsnyc** [comment]
Hi David, thanks for the feedback. The ICP Management Console is running on port 8443. 

We'll add a new output: ICPManagementConsole to make this clear.

**Comment by durera** [comment]
Thanks, do I need to do anything additional from what's covered in the quickstart to configure access? ... when I go to 8443 I get a simple `Error 403 : Access Forbidden` page.

**Comment by vsnyc** [comment]
See Step 5 in the [ICP guide](https://aws-quickstart.s3.amazonaws.com/quickstart-ibm-icp-for-data/doc/ibm-cloud-private-for-data-on-the-aws-cloud.pdf). If you set this up as a valid Route 53 domain then you can access using that, else you will have to modify your hosts file to mimic the cluster DNS name.

**Comment by durera** [comment]
Thanks, we just sussed that out too :) 

Although using https://xxx.elb.xxx.amazonaws.com:31843 worked fine for ICP4D UI, only https://$ClusterName.$VPCDomain:8443 worked for the ICP UI.
